language: go
go:
  - 1.6.3
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get -d github.com/tcnksm/ghr
  - go get github.com/Masterminds/glide
install: glide install
script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
#  - ghr --username $GITHUB_TOKEN --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist
