language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
script:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
#  - ghr --username $GITHUB_TOKEN --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist